
GET http://localhost:3000/coffees

###
GET http://localhost:3000/coffees/6932f4c8-02ee-4804-93ed-b09661f9a336

###
POST http://localhost:3000/coffees
Content-Type: application/json

{
    "name": "Espreço",
    "brand": "Mellita",
    "flavors": ["chocolate", "vanilla"]
}

###
PATCH http://localhost:3000/coffees/ea2c5cfc-bfeb-41d5-8f02-8d37dc6c0338
Content-Type: application/json

{
    "name": "Espressosss",
    "brand": "Mellita",
    "flavors": ["chocolate"]
}

###
DELETE http://localhost:3000/coffees/82052cde-82e1-4b2b-85cf-a9d7cf135883

###
POST http://localhost:3000/coffees/clear-coffees

