version: '3.7'

services:
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=pgsqldb
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nestjs_db

  pgsqldb:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    volumes:
      - ../pgdata:/var/lib/postgresql/data
