version: '3.7'

services:
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=pgsqldb
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nestjs_db
    networks:
      - default

  pgsqldb:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: nestjs_app_network
